basic:
	zig run basic.zig

functions:
	zig run functions.zig

memory:
	zig run memory.zig

struct:
	zig run struct.zig

vectorized:
	zig run vectorized.zig

benchmark:
	zig run benchmark.zig

test:
	zig test tests.zig