basic:
	zig run basic.zig

functions:
	zig run functions.zig

memory:
	zig run memory.zig

struct:
	zig run struct.zig

matrix:
	zig run matrix.zig

sparse:
	zig run sparse.zig

benchmark:
	zig run benchmark.zig

test:
	zig test tests.zig